install.packages("ape")
install.packages("phangorn")
install.packages("picante")
require(ape)
require(phangorn)
require(picante)
x<-read.dna("MNEL1first10aligned.fasta",format="fasta")
d<-dist.dna(x)
write.table(as.matrix(d),"distances.csv")
d2<-dist.dna(x,model="K80")
tr.nj<-nj(d)
plot(tr.nj)
dt.nj<-cophenetic(tr.nj)
dmat<-as.matrix(d)
nms<-rownames(dmat)
dt.nj<-dt.nj[nms, nms]
dt.nj<-as.dist(dt.nj)
plot(dt.nj-d,ylab="residuals", cex=0.5,main="NJ")
#tr.upgma<-upgma(d)
abline(h=0,lty=3) 
fit<-pml(tr.nj,as.phyDat(x))
fit=optim.pml(fit,T)
plot(fit)
set.seed(8)
bs<-bootstrap.pml(fit,bs=100,optNni=T)
treeBS<-plotBS(fit$tree, type="p", bs)
mt<-modelTest(as.phyDat(x),G=F,I=F)
